name: RealmsCommands
version: {$project.version}
main: net.ghostrealms.RealmsCommands
commands:
  balance:
    description: show your economy balance
    aliases: [bal]
  pay:
    description: send money to another user
  setbal:
    description: Set a user's economy balance
    aliases: []
  realms:
    description: Ghost Realms Informational Command
    aliases: []
  uuid:
    description: Get a Player's UUID
    aliases: []